swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API

paths:
  /report/stats:
    get:
      summary: gets event stats for inventory and status
      operationId: app.get_report_stats
      description: gets reading stats
      produces:
      - application/json
      responses:
        200:
          description: current stats
          schema:
            $ref: '#/definitions/ReadingStats'
        400:
          description: Stats do not exist

definitions:
  ReadingStats:
    type: object
    required:
    - num_inventory_readings
    - num_status_readings
    - updated_timestamp
    properties:
      num_inventory_readings:
        type: integer
        example: 1023
      num_status_readings:
        type: integer
        example:  1023
      updated_timestamp:
        type: string
        format: date-time
        example: 2016-08-29TO9:12:33.001Z